/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenU1;

import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Alcan
 */
public class ExpresionesRegulares extends javax.swing.JFrame {

    /**
     * Creates new form ExpresionesRegulares
     */
    public ExpresionesRegulares() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txaEntrada = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnAnalizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txf2 = new javax.swing.JTextField();
        txf1 = new javax.swing.JTextField();
        txf3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        txaEntrada.setColumns(20);
        txaEntrada.setRows(5);
        jScrollPane1.setViewportView(txaEntrada);

        jLabel1.setText("Entrada de texto");

        btnAnalizar.setText("analizar");
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel12.setText("Numero");

        jLabel13.setText("ID");

        jLabel14.setText("No. Control");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAnalizar)
                .addGap(108, 108, 108))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txf1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txf2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txf3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnAnalizar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ArrayList<String> cadenas = new ArrayList<>();
    String filas[] = new String[cadenas.size()];
    File archivo;
    FileWriter escritor;
    String nuevacadena;
    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        // TODO add your handling code here:
        //Ingresa tex Area a lista

        filas = txaEntrada.getText().split("\n");

        for (int i = 0; i < filas.length; i++) {
            cadenas.add(filas[i]);

        }
        validar();
    }//GEN-LAST:event_btnAnalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExpresionesRegulares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExpresionesRegulares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExpresionesRegulares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExpresionesRegulares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExpresionesRegulares().setVisible(true);

            }
        });
    }

    public void validar() {
        try {

            File pre = new File("C:\\Users\\Alcan\\Documents/pre.txt");
            File R1 = new File("C:\\Users\\Alcan\\Documents/R1.txt");
            File R2 = new File("C:\\Users\\Alcan\\Documents/R2.txt");
            File R3 = new File("C:\\Users\\Alcan\\Documents/R3.txt");          
            File Rechazadas = new File("C:\\Users\\Alcan\\Documents/Rechazadas.txt");

            //************************************************************************
            FileWriter fw = new FileWriter(pre.getAbsoluteFile(), true);
            PrintWriter pw = new PrintWriter(fw);

            pw.println(cadenas);
            fw.close();

            String ER1 = "([0-9]+[f|F]*)";//flotantes
            String ER11 = "([0-9])+([.])([0-9])+([f|F]*)";
            String ER111 = "^([0-9])+([.])(0-9)+";//dobles
            String ER1111 = "([0-9]+[d|D]*)";
            int contadorER1 = 0;
            String ER2 = "([A-Za-z]{1}|[$|_]{1})([A-Za-z0-9]*)"; //ID
            int contadorER2 = 0;
            String ER3 = "([A-ZÁÉÍÓÚ]{1}[a-zñáéíóú]*[\\s]*)+";//nombre propio
            int contadorER3 = 0;
            int contador = 0;

            for (int i = 0; i < cadenas.size(); i++) {

                //valores numericos
                if (cadenas.get(i).matches(ER1) | cadenas.get(i).matches(ER11) | cadenas.get(i).matches(ER111) | cadenas.get(i).matches(ER11)) {
                    FileWriter fw2 = new FileWriter(R1.getAbsoluteFile(), true);
                    PrintWriter pw2 = new PrintWriter(fw2);
                    pw2.println(cadenas.get(i));
                    fw2.close();
                    contadorER1++;
                    txf1.setText(contadorER1 + "");
                } else {
//    if(!txaEntrada.getText().matches(ER1) | !txaEntrada.getText().matches(ER11)| 
//       !txaEntrada.getText().matches(ER111)| txaEntrada.getText().matches(ER11)){

                    //validacion de char 
                    if (cadenas.get(i).matches(ER2)) {
                        FileWriter fw3 = new FileWriter(R2.getAbsoluteFile(), true);
                        PrintWriter pw3 = new PrintWriter(fw3);
                        pw3.println(cadenas.get(i));
                        fw3.close();
                        contadorER2++;
                        txf2.setText(contadorER2 + "");

                    } else {

                        //validacion de nombre propio
                        if (cadenas.get(i).matches(ER3)) {
                            FileWriter fw4 = new FileWriter(R3.getAbsoluteFile(), true);
                            PrintWriter pw4 = new PrintWriter(fw4);
                            pw4.println(cadenas.get(i));
                            fw4.close();
                            contadorER3++;
                            txf3.setText(contadorER3 + "");
                        } else {                           
                                    contador++;
                                }
                            }
                        }
                    }
                    }
                }
                FileWriter fw7 = new FileWriter(Rechazadas.getAbsoluteFile(), true);
                PrintWriter pw7 = new PrintWriter(fw7);
                pw7.println(cadenas.get(i));
                fw7.close();
                txfRechazadas.setText("" + contador);

            }

        } catch (Exception e) {
            System.out.println("Error:" + e.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea txaEntrada;
    private javax.swing.JTextField txf1;
    private javax.swing.JTextField txf2;
    private javax.swing.JTextField txf3;
    // End of variables declaration//GEN-END:variables
}
